### ISSUE TITLE
设置头字段中set-cookie为对应cookie  字段类型报错

### ISSUE THREAD

**Issue by homer-wh** [xiongwilee/Gracejs#49]
node版本: v8.1.4
模板引擎: Nunjucks

错误信息:
/middleware/proxy/index.js:390
    ctx.res._headers['set-cookie'] = ctx.res._headers['set-cookie'].concat(cookies);
                                                                                                            ^
TypeError: Cannot read property 'concat' of undefined

**Comment by xiongwilee** [comment]
已修复：
 https://github.com/xiongwilee/Gracejs/commit/95c4ffb80a0c88390ddbb13b7b16018e9de1d3e3
