### ISSUE TITLE
proxy代理数据问题

### ISSUE THREAD

**Issue by huangdebin** [xiongwilee/Gracejs#51]
大神，你好！我想代理第三方接口，使用this.proxy('college_api:admin/class/class-list?userAccount=admin&token=xxx');为什么参数无法传到api里去呢？可以大概的说明一下，可能有哪些原因导致呢？感激！！！

**Comment by xiongwilee** [comment]
1. API接口会解析get参数吗（是不是只取post参数）？
2. this.proxy方法会默认把当前请求的参数带给后端，你不用再做处理；
3. 实在不行可以看看源码：https://github.com/xiongwilee/Gracejs/blob/master/middleware/proxy/index.js#L218
