### ISSUE TITLE
如何提高单点TPS, QPS 

### ISSUE THREAD

**Issue by yongjun310** [xiongwilee/Gracejs#66]
试着用jmeter 30个并发，将GraceJs proxy代理到www.baidu.com,  发现throughput只有140左右，请问怎么提升单节点的吞吐量呢？

**Comment by yongjun310** [comment]
数据库我已经删除了

**Comment by xiongwilee** [comment]
Gracejs proxy功能依赖的request.js已经处于停止维护状态了（https://github.com/request/request/issues/3142）；加之以Nodejs将使用llhttp替代http-parser；

近期准备把proxy中间件用Nodejs原生实现，以评估其性能短板，同时迎接llhttp带来的性能飞跃，敬请期待

**Comment by yongjun310** [comment]
有没有微信或者qq讨论群呢，也许可以一起哈

**Comment by xiongwilee** [comment]
可以加我微信： xiongwilee

**Comment by yongjun310** [comment]
在这个commit解决了https://github.com/xiongwilee/Gracejs/pull/69/commits/473cd0248f438bc5bdb07e2b974ed0904dd98edd
