### ISSUE TITLE
npm run dev 后 访问127.0.0.1:3000  报错 Cannot read property 'store' of undefined

### ISSUE THREAD

**Issue by neu-yuyang** [xiongwilee/Gracejs#70]
![image](https://user-images.githubusercontent.com/26411479/83711810-d4742080-a656-11ea-8003-8c0cb0ead60e.png)

**Comment by andynicoo** [comment]
我也遇到这个问题

**Comment by zhiyouth** [comment]
我也是，直接劝退

**Comment by master1lan** [comment]
猜测是默认配置的token过期了，直接将/src/app.js内session配置注释掉就能运行

**Comment by master1lan** [comment]
> 猜测是默认配置的token过期了，直接将/src/app.js内session配置注释掉就能运行

`// session配置，默认存在cookie中
  // const sessionConfig = config.session[appName] || {};
  // vapp.use(Middles.session(Object.assign({
  //   key: `GRACE:${appName}`
  // }, sessionConfig), vapp));`

**Comment by xiongwilee** [comment]
感谢反馈， 已修复： https://github.com/xiongwilee/Gracejs/commit/2096612795e361ca065dadb36a9d1764b2119fc3
