### ISSUE TITLE
session中间件报错，this.session是undefined

### ISSUE THREAD

**Issue by thinkincloud** [xiongwilee/Gracejs#76]
还能更新吗，session中间件报错，this.session是undefined

**Comment by xiongwilee** [comment]
好的，明天解决。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月3日(周二) 上午10:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [xiongwilee/Gracejs] 还能更新吗，session中间件报错，this.session是undefined (Issue #76)




 
还能更新吗，session中间件报错，this.session是undefined

**Comment by xiongwilee** [comment]
修复了，更新后看下？https://github.com/xiongwilee/Gracejs/commit/6d9a76e4763c3dfabc2d63c74cd0630bb85e678b
